Section "InputClass"
    Identifier      "calibration"
    MatchProduct    "ADS7846 Touchscreen"
    Option  "MinX"  "3936"
    Option  "MaxX"  "227"
    Option  "MinY"  "268"
    Option  "MaxY"  "3880"
    Option  "SwapXY" "1"
    Option  "InvertX" "0"
    Option  "InvertY" "0"
    Option  "EmulateThirdButton" "1"
    Option  "EmulateThirdButtonTimeout" "750"
    Option  "EmulateThirdButtonThreshold" "30"
EndSection
